"""Add FrenchSite variant

Revision ID: 3bf0064b5cde
Revises: c85455bba362
Create Date: 2024-05-27 11:25:59.279590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf0064b5cde'
down_revision: Union[str, None] = 'c85455bba362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('french_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('useful_energy_at_1_megawatt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('french_site')
    # ### end Alembic commands ###
