"""Add polymorphism to Site

Revision ID: c85455bba362
Revises: dd83f666100b
Create Date: 2024-05-26 20:30:36.312181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85455bba362'
down_revision: Union[str, None] = 'dd83f666100b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('italian_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sites', sa.Column('variant', sa.String(), nullable=True))
    op.create_index(op.f('ix_sites_variant'), 'sites', ['variant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_variant'), table_name='sites')
    op.drop_column('sites', 'variant')
    op.drop_table('italian_site')
    # ### end Alembic commands ###
